use snapbuy;
show tables;
-- query 1
select * from USR WHERE UPPER(USER_NAME) LIKE 'CL%';
-- query 2
select ORDER_ID, SHIPPER_NAME AS "SHIPPER NAME", SHIPPER_ADDRESS, SHIPPER_RATING FROM
ORDE O NATURAL JOIN SHIPPER S WHERE S.SHIPPER_RATING = 9;
-- query 3
UPDATE PRODUCT P SET P.PRODUCT_ID = P.PRODUCT_ID +1000 WHERE P.PRODUCT_ID = ANY 
( SELECT PRODUCT_ID FROM INVENTORY WHERE QUANTITY > 5);
-- QUERY 4
SELECT COUPON_DISCOUNT, COUPON_EXPIRYDATE, ORDER_ID, TOTAL_COST FROM COUPON C 
INNER JOIN ORDE O ON C.USER_ID = O.USER_ID WHERE C.COUPON_EXPIRYDATE <= '2-16-2022'
AND O.TOTAL_COST = 90;
-- QUERY 5
SELECT * FROM CART WHERE PRODUCT_ID IN (SELECT DISTINCT PRODUCT_ID FROM BELONGSTO WHERE
CATEGORY_ID IN ( SELECT CATEGORY_ID FROM CATEGORY WHERE CATEGORY_NAME = 'Mraz Inc'));
-- QUERY 6
SELECT * FROM CART WHERE PRODUCT_ID IN 
( SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_COST < 
( SELECT AVG(PRODUCT_COST) FROM PRODUCT ORDER BY PRODUCT_COST)) LIMIT 10;
-- QUERY 7
SELECT SUM(QUANTITY*PRICE) FROM CART WHERE USER_ID in
( SELECT USER_ID FROM COUPON WHERE COUPON_DISCOUNT > 
(SELECT AVG(COUPON_DISCOUNT) FROM COUPON));
-- QUERY 8
ALTER TABLE BILL
ADD column BILL_INFO TEXT;
SELECT * FROM BILL LIMIT 10;
ALTER TABLE BILL
DROP COLUMN BILL_INFO;
SELECT * FROM BILL LIMIT 10;
-- QUERY 9
SELECT PRODUCT_NAME , COUNT(*) AS "ALL 5 STAR PRODUCTS" FROM PRODUCT WHERE PRODUT_RATING=5 GROUP BY
PRODUCT_NAME;
SELECT PRODUCT_COST, COUNT(*) AS "ALL COST OF 5 STAR PRODUCT" FROM PRODUCT WHERE PRODUT_RATING =5 GROUP BY PRODUCT_COST ORDER BY PRODUCT_COST DESC;
-- QUERY 10
SELECT * FROM FEEDBACK RIGHT JOIN USR ON FEEDBACK.USER_ID = USR.USER_ID WHERE
FEEDBACK_RATING = 4 AND PRODUCT_NAME IN (SELECT PRODUCT_NAME FROM PRODUCT
WHERE PRODUCT_COST > 500);
-- QUERY 11
SELECT ORDER_ID, TOTAL_COST FROM ORDE WHERE TOTAL_COST between 30 AND 40;
-- query 12
SELECT USER_NAME, COUNT(*) AS "PRIME USERS" FROM USR INNER JOIN CART ON USR.USER_ID
= CART.USER_ID WHERE CART.PRICE > 8000 GROUP BY USER_NAME ORDER BY USER_NAME;
